/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SubmittedStudent = IDL.Record({
  'id' : IDL.Nat,
  'institution' : IDL.Text,
  'name' : IDL.Text,
  'rank' : IDL.Opt(IDL.Nat),
  'year' : IDL.Nat,
  'section' : IDL.Text,
  'submittedAt' : IDL.Int,
  'department' : IDL.Text,
  'examType' : IDL.Text,
});

export const idlService = IDL.Service({
  'deleteSubmittedStudent' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getSubmittedStudents' : IDL.Func([], [IDL.Vec(SubmittedStudent)], ['query']),
  'ping' : IDL.Func([], [IDL.Text], ['query']),
  'submitStudent' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Nat),
        IDL.Text,
        IDL.Nat,
      ],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SubmittedStudent = IDL.Record({
    'id' : IDL.Nat,
    'institution' : IDL.Text,
    'name' : IDL.Text,
    'rank' : IDL.Opt(IDL.Nat),
    'year' : IDL.Nat,
    'section' : IDL.Text,
    'submittedAt' : IDL.Int,
    'department' : IDL.Text,
    'examType' : IDL.Text,
  });
  
  return IDL.Service({
    'deleteSubmittedStudent' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getSubmittedStudents' : IDL.Func(
        [],
        [IDL.Vec(SubmittedStudent)],
        ['query'],
      ),
    'ping' : IDL.Func([], [IDL.Text], ['query']),
    'submitStudent' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Nat),
          IDL.Text,
          IDL.Nat,
        ],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };